package com.CRBProjectt.CRBProjectt.domain;

public enum Category {

	CREDITDECAISSE, CREDITDEFONDSDEROULEMENT, CREDITDEDESSAISISSEMENT, CREDITDESTOCKAGE, CREDITDESCOMPTE,
	CREDITRELAIS, CREDOCIMPAYE, CREDITDESOUDURE, CREDITDEFAIREVALOIR, CREDITDEMBOUCHE, CREDITDECAMPAGNE,
	AUTRESCREDITSADECAISSEMENT, CREDITSPERSONNELS, CREDITVEHICULE, PRETSHYPOTHECAIRES, LEASINGIMMOBILIER,
	LEASINGMOBILIER, CREDITDINVESTISSEMENT, CREDITDOCUMENTAIRE, LACAUTION, LAVAL, LACCEPTATION, AUTRECREDITDESIGNATURE
}
