package com.CRBProjectt.CRBProjectt.domain;

public enum Nature {

	CREDITENCOMPTECOURANT, ESCOMPTESDEFFETSCOMMERCIAUX, AUTRESCREDITSACOURTTERME, HABITATAMOYENTERME,
	VEHICULESUTILITAIRESAMOYENTERME, AUTRESEQUIPEMENTSAMOYENTERME, AUTRESCREDITSAMOYENTERME,
	HABITATALONGTERME, EQUIPEMENTALONGTERME, AUTRESCREDITSALONGTERME, AUTRESCREDITSADECAISSEMENT,
	CREDOCS, ACCEPTATIONS, AUTRESCREDITSDESIGNATURE, 
}
